FROM rust:1.61 AS builder
COPY config /.cargo/config
RUN git clone https://github.com/denverdino/wagi && echo OK
RUN cd wagi && git checkout with_cache && cargo build --release

FROM debian:bullseye-slim
COPY sources.list /etc/apt/sources.list
COPY --from=builder /wagi/target/release/wagi /usr/local/bin/wagi
COPY --from=builder /wagi/examples /examples
CMD [ "wagi", "-l", "0.0.0.0:8080", "-c", "/examples/modules.toml" ]292184